title: LifeWatch e-lab user manual
description: A quick introdution to the LifeWatch e-lab
theme: just-the-docs

url: https://lifewatch.github.io/elab-documentation

footer_content: "©️ 2023 LifeWatch BE"

logo: "/assets/images/LifeWatch_official_0.png"

aux_links:
  "Report feedback":
    - "https://github.com/lifewatch/elab-documentation/issues"
