title: LifeWatch e-lab user manual
description: A quick introdution to the LifeWatch e-lab
theme: just-the-docs

url: https://lifewatch.github.io/elab-documentation

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
